# Helix
# https://helix-editor.com
# https://docs.helix-editor.com/configuration.html
# https://github.com/helix-editor/helix/blob/master/helix-term/src/keymap/default.rs

# Appearance -------------------------------------------------------------------

theme = 'catppuccin_frappe'

[editor]
rulers = [81]
line-number = 'relative'
color-modes = true

[editor.whitespace]
render = 'all'
characters = { newline = '¬' }

# [editor.indent-guides]
# render = true

# Key bindings -----------------------------------------------------------------

[keys.normal]
ret = 'command_mode'
'#' = 'toggle_comments'
S = 'surround_add'
V = 'select_textobject_around'

[keys.normal.space]
space = ['keep_primary_selection', 'collapse_selection']
tab = 'flip_selections'
backspace = 'collapse_selection'
# Formatting and parsing date-time
# Format date to 2006-01-02 Mon
D = ':pipe date -d "$(cat)" "+%F %a" | tr -d "\\n"'

[keys.insert]
'A-o' = 'add_newline_above'
'A-ret' = 'add_newline_below'

# Insert date (2006-01-02 Mon 15:04)
'C-d' = ':insert-output date "+%F %a" | tr -d "\\n"'
