# Helix
# https://helix-editor.com
# https://docs.helix-editor.com/languages.html
# https://github.com/helix-editor/helix/blob/master/languages.toml

[[language]]
name = 'ruby'
file-types = ['cr']
language-server = { command = 'crystalline' }
