#!/bin/sh

eval $(battery '
  STATUS=$status
  PERCENTAGE=$percentage
  CAPACITY=$capacity
')

case $STATUS in
  Full) status_symbol= ;;
  Discharging) status_symbol=⚡ ;;
  Charging) status_symbol= ;;
esac

if test $PERCENTAGE -gt 90; then
  percentage_symbol=
elif test $PERCENTAGE -gt 60; then
  percentage_symbol=
elif test $PERCENTAGE -gt 30; then
  percentage_symbol=
elif test $PERCENTAGE -gt 10; then
  percentage_symbol=
elif test $PERCENTAGE -gt 0; then
  percentage_symbol=
fi

# Design capacity tells how worn off my battery is.
# https://i3wm.org/i3status/manpage.html#_battery
if test $PERCENTAGE = 100; then
  percentage=$CAPACITY
else
  percentage=$PERCENTAGE
fi

echo "$status_symbol $percentage_symbol $percentage%"

# Icons
# https://unicode-table.com/en/26A1/
# https://fontawesome.com/icons/plug
# https://fontawesome.com/icons/battery-full
# https://fontawesome.com/icons/battery-three-quarters
# https://fontawesome.com/icons/battery-half
# https://fontawesome.com/icons/battery-quarter
# https://fontawesome.com/icons/battery-empty
