#!/bin/sh

selection=${1:-clipboard}

get() { xclip -out -selection $selection; }

case $BLOCK_BUTTON in
  1) notify-send Clipboard "$(get)" ;;
  2) xclip-clear ;;
esac

export selection=$(get)

password_key=$(
  yaml-to-json < $XDG_CONFIG_HOME/passwords.yml |
  jq --raw-output 'to_entries[] | select(.value[-1] == env.selection).key'
)

if test "$password_key"; then
  symbol=
  text=$password_key
else
  symbol=
  text=$(get | slice 1-7)
fi

echo "$symbol $text"

# Icons
# https://fontawesome.com/icons/clipboard
# https://fontawesome.com/icons/lock
