#!/bin/sh

interface=$1
container=/sys/class/net/$interface
mode=$(cat $container/link_mode)

[ $mode = 1 ] &&

net-speed $interface |
sed \
  --expression s/'\.[0-9]\+'//g \
  --expression s/'[0-9]\+ B'/'0 KB'/g
