# Alacritty
# https://alacritty.org
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

import:

  # Color scheme: Dracula (https://draculatheme.com/alacritty)
  - ~/code~/dracula/alacritty/dracula.yml

  # Color scheme: Catppuccin Frappe (https://catppuccin.com)
  - ~/.local/share/github.com/catppuccin/alacritty/catppuccin.yml

  # CSI u mode
  - ~/code~/alacritty-extended-keys/keys.yml

# Appearance -------------------------------------------------------------------

# Add a bit of transparency to reduce eye strain.
window:
  opacity: 0.99

font:
  size: 16.0
  normal:
    family: JetBrains Mono

selection:
  save_to_clipboard: true

cursor:
  style:
    shape: Beam
    blinking: On

# Keyboard ---------------------------------------------------------------------

# Keys:
# https://docs.rs/glutin/latest/glutin/event/enum.VirtualKeyCode.html
key_bindings:
  - { key: N, mods: Control|Shift, action: CreateNewWindow }
  - { key: N, mods: Command, action: CreateNewWindow }
