window:
  dimensions:
    columns: 80
    lines: 24

# Dracula
# https://draculatheme.com
# https://github.com/alexherbo2/alacritty-dracula-theme
colors:
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'
  cursor:
    text: '0x44475a'
    cursor: '0xf8f8f2'
  normal:
    black: '0x282a36'
    red: '0xff5555'
    green: '0x50fa7b'
    yellow: '0xf1fa8c'
    blue: '0x6272a4'
    magenta: '0xff79c6'
    cyan: '0x8be9fd'
    white: '0xf8f8f2'
  bright:
    black: '0x44475a'
    red: '0xff8888'
    green: '0x82fba0'
    yellow: '0xf7fcbd'
    blue: '0x828fb7'
    magenta: '0xffacdc'
    cyan: '0xbdf3fe'
    white: '0xffffff'
  dim:
    black: '0x14151b'
    red: '0xff2222'
    green: '0x1ef956'
    yellow: '0xebf85b'
    blue: '0x4d5b86'
    magenta: '0xff46b0'
    cyan: '0x59dffc'
    white: '0xe6e6d1'

shell:
  program: elvish
