# Alacritty
# https://github.com/alacritty/alacritty
#
# Theme: Dracula (https://draculatheme.com/alacritty)

# Nushell
# https://nushell.sh
#
# Use the latest version of Nushell.
shell:
  program: /home/taupiqueur/repositories/github.com/nushell/nushell/target/release/nu

import:
  - /home/taupiqueur/projects/alacritty-extended-keys/keys.yml
  - /home/taupiqueur/repositories/github.com/dracula/alacritty/dracula.yml

window:
  dimensions:
    columns: 80
    lines: 24

font:
  normal:
    family: PragmataPro

# Enable cursor blinking
cursor:
  style:
    blinking: On

# Enable audio bell.
#
# XDG sound theme
# https://gitlab.freedesktop.org/xdg/xdg-sound-theme
bell:
  command:
    program: mpv
    args: ['-no-config', '-no-video', '-no-terminal', '/home/taupiqueur/repositories/gitlab.freedesktop.org/xdg/xdg-sound-theme/stereo/bell.oga']

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }
