# Alacritty
# https://github.com/alacritty/alacritty
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

import:

  # Color scheme – https://draculatheme.com/alacritty
  - /Users/taupiqueur/projects/dracula/alacritty/dracula.yml

  # CSI u mode – https://github.com/alexherbo2/alacritty-extended-keys
  - /Users/taupiqueur/projects/alacritty-extended-keys/keys.yml

# Appearance ───────────────────────────────────────────────────────────────────

# Add a bit of transparency to reduce eye strain.
window:
  opacity: 0.99

font:
  size: 16.0
  normal:
    family: PragmataPro

cursor:
  style:
    shape: Beam
    blinking: On

# Keyboard ─────────────────────────────────────────────────────────────────────

# Keys:
# https://docs.rs/glutin/latest/glutin/event/enum.VirtualKeyCode.html
key_bindings:
  - { key: N, mods: Control|Shift, action: CreateNewWindow }
  - { key: N, mods: Command, action: CreateNewWindow }
