import:
  - /home/taupiqueur/projects/alacritty-extended-keys/keys.yml
  - /home/taupiqueur/repositories/github.com/dracula/alacritty/dracula.yml

window:
  dimensions:
    columns: 80
    lines: 24

shell:
  program: nu

font:
  normal:
    family: PragmataPro

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }
