# Alacritty
# https://github.com/alacritty/alacritty

import:

  # Color scheme – https://draculatheme.com/alacritty
  - /home/taupiqueur/repositories/github.com/dracula/alacritty/dracula.yml

  # CSI u mode – https://github.com/alexherbo2/alacritty-extended-keys
  - /home/taupiqueur/projects/alacritty-extended-keys/keys.yml

# General ──────────────────────────────────────────────────────────────────────

# Nushell
# https://nushell.sh
#
# Use the latest version of Nushell.
shell:
  program: /home/taupiqueur/repositories/github.com/nushell/nushell/target/release/nu

# Initial terminal size:
window:
  dimensions:
    columns: 80
    lines: 24

# Appearance ───────────────────────────────────────────────────────────────────

# Add a bit of transparency to reduce eye strain.
background_opacity: 0.99

font:
  size: 11.0
  normal:
    family: PragmataPro

cursor:
  style:
    blinking: On

# Sound ────────────────────────────────────────────────────────────────────────

# Audio bell
#
# XDG sound theme
# https://gitlab.freedesktop.org/xdg/xdg-sound-theme
bell:
  command:
    program: mpv
    args: ['-no-config', '-no-video', '-no-terminal', '/home/taupiqueur/repositories/gitlab.freedesktop.org/xdg/xdg-sound-theme/stereo/bell.oga']

# Keyboard ─────────────────────────────────────────────────────────────────────

key_bindings:
  - { key: F1, mods: Shift, command: { program: chromium, args: ['https://github.com/alacritty/alacritty/blob/master/alacritty.yml'] } }
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
