window:
  dimensions:
    columns: 80
    lines: 24

shell:
  program: elvish

font:
  normal:
    family: PragmataPro

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }
