evaluate-commands %sh{
  find -L "$kak_config/autoload" -type f -name '*.kak' -exec printf 'source "%s";' {} +
}

source "%val{config}/kakrc"

evaluate-commands %sh{
  if [ -f '.kakrc' -a -r '.kakrc' ]; then
    echo "source '.kakrc'"
  fi
}
