# Starship
# https://starship.rs
eval "$(starship init "$(basename "$0")")"

# TTY settings
if [ "$TERM" = 'linux' ]; then
  # Color scheme
  # https://draculatheme.com/tty
  . ~/repositories/github.com/dracula/tty/dracula-tty.sh

  # Fonts
  # /run/current-system/sw/share/consolefonts
  setfont Lat2-Terminus16
fi

# Broot
# https://dystroy.org/broot/
. ~/.config/broot/launcher/bash/br

# RVM
# https://rvm.io
[ -s ~/.rvm/scripts/rvm ] && . ~/.rvm/scripts/rvm

# Aliases
alias @='fork'
alias p='echo'
alias _='rm -Rf'
alias md='mkdir -p'

# rpg-cli — your filesystem as a dungeon!
# https://github.com/facundoolano/rpg-cli
rpg() {
  rpg-cli "$@"
  cd "$(rpg-cli --pwd)"
}

# NixOS
# https://nixos.org
alias nix-update='sudo nixos-rebuild switch'
alias nix-upgrade='sudo nixos-rebuild switch --upgrade --keep-going --fallback'
alias nix-gc='sudo nix-collect-garbage --delete-old'

# Shell
alias na='nix-shell-attr'
alias ns='nix-shell --command nu'
alias np='nix-shell --command nu --packages'

# Compiling
alias nix-cargo='nix-shell --run '"'"'cargo build --release'"'"' --packages pkg-config rustup rustc cargo openssl'
alias nix-shards='shards build --release --production'

# KDE
# https://kde.org
alias kcm='kcmshell5-fzf'

# Sleep
alias z='sudo systemctl suspend'
alias zz='swaymsg exit'
alias zzz='sudo shutdown now'

# SSH
alias ssh!='
  rm -Rf ~/.cache/ssh/sessions
  mkdir ~/.cache/ssh/sessions
'

# nginx
# https://nginx.org
alias nginx='sudo nginx -c /etc/nginx/nginx.conf'

# Wallpapers
bg() {
  swaymsg output '*' bg "$@" fill
}

# Keyboard
alias fr='swaymsg input type:keyboard xkb_file ~/repositories/github.com/fabi1cazenave/qwerty-lafayette/dist/qwerty-l.xkb'
alias kbd='swaymsg input 1:1:AT_Translated_Set_2_keyboard events toggle'

# procs
# https://github.com/dalance/procs
alias ps='procs'

# htop
# https://htop.dev
alias top='htop'

# rsync
# https://rsync.samba.org
alias cp='rsync --archive --compress --hard-links --info=progress2 --delete'

# rm
alias rm='rm -Rf'
alias rm!='rm -Rf ~/.local/share/Trash'

# bat
# https://github.com/sharkdp/bat
alias cat='bat'

# fd
# https://github.com/sharkdp/fd
alias find='fd'

# ripgrep
# https://github.com/BurntSushi/ripgrep
alias grep='rg'

# curl
# https://curl.haxx.se
alias curl='curl -sSL'

# archiver
# https://github.com/mholt/archiver
alias x='arc unarchive'

# https://github.com/bugaevc/wl-clipboard
alias yk='wl-copy'

# wf-recorder
# https://github.com/ammen99/wf-recorder
rec() {
  wf-recorder -f $(new-file '' .mkv) "$@"
}

# XWayland
x11() {
  export GDK_BACKEND='x11'
  export QT_QPA_PLATFORM='xcb'
}

# Zellij
# https://zellij.dev
alias mux='zellij'

# tab
# https://github.com/austinjones/tab-rs
alias t='tab'
alias t~='tab home'
alias tl='tab --list'
alias tw='tab --close'
alias tW='tab --shutdown'

# Pueue
# https://github.com/Nukesor/pueue
alias q='pueue'
alias Q='fork pueued'
alias qj='pueue parallel'
alias qa='pueue add'
alias qi='pueue status'
alias qI='pueue clean'

alias ql='pueue-fzf log'
alias qL='pueue-fzf follow'

alias qp='pueue-fzf pause'
alias qP='pueue-fzf start'

alias qw='pueue-fzf kill'
alias qW='pueue shutdown'

# synapse
# https://synapse-bt.org
alias s='sycli'
alias S='pueue add synapse'
alias sa='sycli add'
alias si='sycli status'
alias sl='sycli list'
alias sp='sycli-fzf pause'
alias sP='sycli-fzf resume'
alias sw='sycli-fzf del --files'
alias sW='pkill synapse'

# The Lounge
# https://thelounge.chat
alias irc='pueue add thelounge start'

# kakoune.cr
# https://github.com/alexherbo2/kakoune.cr
alias k='kcr edit'
alias K='kcr-fzf-shell'
alias KK='K --working-directory .'
alias ks='kcr shell --session'
alias ksa='kcr shell --session "${PWD##*/}"'
alias kl='kcr list'
alias a='kcr attach'
alias :='kcr send'
alias :cd='kcr send cd "$PWD"'
alias cd:='cd $(kcr get --raw --shell pwd)'
alias :br='KK broot'
alias :st='KK sidetree'
alias :cat='kcr cat --raw'

alias val='kcr get --value'
alias opt='kcr get --option'
alias reg='kcr get --register'

# Git
# https://git-scm.com
alias g='git'

# Change the working directory to the Git root:
alias @cd='cd "$(git rev-parse --show-toplevel)"'

# gitui
# https://github.com/extrawurst/gitui
alias G='gitui'

# GitHub CLI
# https://cli.github.com
alias gist='gh gist create --web'
alias gv='gh repo view --web'

gc() {
  repository=$1
  gh repo clone "$repository" ~/repositories/github.com/"$repository"
}

gg() {
  git add .
  git discard
  git-gc-all-ferocious
  git push
  git pull
}

GG() {
  for repository in ~/projects/* ~/projects/fork/* ~/projects/dracula/* ~/gist/* ~/repositories/github.com/*/* ~/repositories/gitlab.com/*/* ~/repositories/gitlab.freedesktop.org/*/*
  do
    cd $repository
    pwd | pastel paint green
    git add .
    git discard
    git-gc-all-ferocious
    git pull
  done
}

# Broot
# https://dystroy.org/broot/
alias .='br .'

# exa
# https://the.exa.website
alias l='exa --icons'
alias la='exa --icons --all'
alias ll='exa --icons --git --long'
alias lla='exa --icons --git --long --all'
alias T='exa --tree'
alias ta='exa --tree --all'

# Batch
# https://github.com/alexherbo2/batch
alias batch='batch --editor kak'
alias rn='batch --map '"'"'rename "$1" "$2"'"'"''
alias cv='batch --map '"'"'convert "$1" "$2"'"'"''
alias rl='batch --map '"'"'relink "$1" "$2"'"'"''

# Chronic
# https://github.com/alexherbo2/chronic
alias cr='chronic'

# File manager
alias d='fork dolphin'

# Web browser
alias b='fork chromium'

# mpv
# https://mpv.io
alias m='mpv'
alias ms='mpv -shuffle'

# mpv – streams
alias mp='mpv ~/.config/streams.m3u'
alias mpe='kak ~/.config/streams.m3u'

# mpv – image
alias mi='mpv -config-dir ~/.config/mpv/profiles/image'

# mpv – audio
alias ma='mpv -config-dir ~/.config/mpv/profiles/audio'

# mpv – filter
alias mx='mpv -config-dir ~/.config/mpv/profiles/filter'

# https://ytdl-org.github.io/youtube-dl/
alias y='youtube-dl'

# Pandoc
# https://pandoc.org
alias pandoc='pandoc --defaults ~/.config/pandoc/config.yml'

# Password
# https://github.com/alexherbo2/password
alias pc='password create'
alias pg='password get'
alias pe='password edit'
pm() {
  password menu | fzf --header='Select a password to copy' --prompt='(p)>' |
  xargs password get -- |
  wl-copy
}

# Ruby on Rails
# https://rubyonrails.org
alias r='rails'
alias rr='rails-routes'
