xrdb ~/.Xresources
xkbcomp ~/repositories/github.com/fabi1cazenave/qwerty-lafayette/dist/qwerty-l.xkb $DISPLAY
xmodmap ~/.Xmodmap
feh --bg-fill ~/images/wallpapers/jojo-no-kimyou-na-bouken/josuke-higashikata-crazy-diamond.png
xcompmgr &
dunst &
i3
