= Search

Search command.

== Usage

Enter `search` and start typing to search.
Press `Tab` to skim through the occurrences.
Show search with `show-search` or enter search mode then `Escape`.

== Configuration

Show search:

== add-cursor-character-unicode-expansion

Show Unicode value in the status line.

Run `add-cursor-character-unicode-expansion` and add `%opt{cursor_character_unicode}` expansion to your status line.

--------------------------------------------------------------------------------
add-cursor-character-unicode-expansion
set-option global modelinefmt '%opt{cursor_character_unicode}'
--------------------------------------------------------------------------------

add `%opt{cursor_character_unicode}` expansion.

== show-selected-text

--------------------------------------------------------------------------------
show-selected-text
--------------------------------------------------------------------------------

Blue (alpha-blended) face:

--------------------------------------------------------------------------------
set-face global SelectedText "default,rgba:%opt{blue}%opt{selection_alpha}" # Blue (alpha-blended)
--------------------------------------------------------------------------------

== hide-selected-text

--------------------------------------------------------------------------------
show-search
--------------------------------------------------------------------------------

Enter search mode:

--------------------------------------------------------------------------------
map -docstring 'search' global normal f ':search<ret>'
--------------------------------------------------------------------------------

Enter a specific search mode:

--------------------------------------------------------------------------------
map -docstring 'search (replace)' global normal f ':search<ret>r'
map -docstring 'search (extend)' global normal F ':search<ret>e'
map -docstring 'search (append)' global normal <a-f> ':search<ret>a'
--------------------------------------------------------------------------------

White (alpha-blended) faces:

--------------------------------------------------------------------------------
set-face global Search "default,rgba:%opt{white}%opt{selection_alpha}" # White (alpha-blended)
set-face global SearchBackground 'white'
set-face global SearchOccurrence 'yellow+b'
--------------------------------------------------------------------------------

== Commands

- `search`
- `show-search`
- `hide-search`

== Prompt commands

- `Tab` ⇒ Next
- `Shift+Tab` ⇒ Previous
- `Control+T` ⇒ Window top
- `Control+B` ⇒ Window bottom

== Faces

- `Search`
- `SearchBackground`
- `SearchOccurrence`
