[colors.primary]
background = '#171717'
foreground = '#ffffff'

[colors.cursor]
text = 'CellForeground'
cursor = '#8b8b8b'

[colors.vi_mode_cursor]
text = 'CellForeground'
cursor = '#8b8b8b'

[colors.selection]
text = 'CellForeground'
background = '#314f78'

[colors.search.matches]
foreground = 'CellForeground'
background = '#303030'

[colors.search.focused_match]
foreground = 'CellForeground'
background = '#314f78'

[colors.hints.start]
foreground = '#ffffff'
background = '#999900'

[colors.hints.end]
foreground = '#ffffff'
background = '#999900'

[colors.line_indicator]
foreground = '#ffffff'
background = '#303030'

[colors.footer_bar]
foreground = '#ffffff'
background = '#303030'

[colors.normal]
black = '#000000'
red = '#990000'
green = '#00a600'
yellow = '#999900'
blue = '#0000b2'
magenta = '#b200b2'
cyan = '#00a6b2'
white = '#bfbfbf'

[colors.bright]
black = '#666666'
red = '#e50000'
green = '#00d900'
yellow = '#e5e500'
blue = '#0000ff'
magenta = '#e500e5'
cyan = '#00e5e5'
white = '#e5e5e5'
