[colors.primary]
background = '#171717'
foreground = '#ffffff'

[colors.cursor]
text = 'CellForeground'
cursor = '#8b8b8b'

[colors.vi_mode_cursor]
text = 'CellForeground'
cursor = '#8b8b8b'

[colors.selection]
text = 'CellForeground'
background = '#314f78'

[colors.search.matches]
foreground = 'CellForeground'
background = '#303030'

[colors.search.focused_match]
foreground = 'CellForeground'
background = '#314f78'

[colors.hints.start]
foreground = '#ffffff'
background = '#999900'

[colors.hints.end]
foreground = '#ffffff'
background = '#999900'

[colors.line_indicator]
foreground = '#ffffff'
background = '#303030'

[colors.footer_bar]
foreground = '#ffffff'
background = '#303030'

[colors.normal]
black = '#000000'
red = '#ff3333'
green = '#40ff40'
yellow = '#ffff33'
blue = '#4c4cff'
magenta = '#ff4cff'
cyan = '#4cf3ff'
white = '#bfbfbf'

[colors.bright]
black = '#666666'
red = '#ff7f7f'
green = '#73ff73'
yellow = '#ffff7f'
blue = '#9999ff'
magenta = '#ff7fff'
cyan = '#7fffff'
white = '#e5e5e5'
