#!/bin/sh

# install
# brew install gum yt-dlp

set -e
gum format "Choose where to download files:"
TARGET_DIRECTORY=$(gum file --file=false --directory)
echo "> $TARGET_DIRECTORY"
while :
do
  gum format "Enter a YouTube URL:"
  URL=$(gum input --placeholder="YouTube URL")
  test -n "$URL"
  gum spin --title="Downloading '$URL' at '$TARGET_DIRECTORY'..." -- yt-dlp -P "$TARGET_DIRECTORY" -- "$URL"
  gum format "Downloaded '$URL' at '$TARGET_DIRECTORY'."
done
