set-face global ts_attribute attribute
set-face global ts_comment comment
set-face global ts_conceal Error
set-face global ts_constant "rgb:%opt{red_color}" # value
set-face global ts_constructor value
set-face global ts_diff_delta changed
set-face global ts_diff_minus deleted
set-face global ts_diff_plus added
set-face global ts_error DiagnosticError
set-face global ts_function function
set-face global ts_hint DiagnosticHint
set-face global ts_info DiagnosticInfo
set-face global ts_keyword keyword
set-face global ts_label Error
set-face global ts_markup_bold +b
set-face global ts_markup_heading header
set-face global ts_markup_heading_1 title
set-face global ts_markup_italic +i
set-face global ts_markup_link link
set-face global ts_markup_list list
set-face global ts_markup_quote string
set-face global ts_markup_raw mono
set-face global ts_markup_raw_block block
set-face global ts_markup_strikethrough +s
set-face global ts_namespace "rgb:%opt{green_color}" # module
set-face global ts_operator operator
set-face global ts_property variable
set-face global ts_punctuation operator
set-face global ts_special meta
set-face global ts_spell Error
set-face global ts_string string
set-face global ts_tag keyword
set-face global ts_text Error
set-face global ts_type type
set-face global ts_variable variable
set-face global ts_warning DiagnosticWarning
