complete -c kak -o c -x -a "(kak -l)" -d "connect to session"
complete -c kak -o C -x -a "(kak -l)" -d "connect or create session"
complete -c kak -o e -x -d "execute commands on client initialization"
complete -c kak -o E -x -d "execute commands on server initialization"
complete -c kak -o n -d "ignore kakrc"
complete -c kak -o s -x -d "set session name"
complete -c kak -o d -d "run in headless mode"
complete -c kak -o p -x -d "send commands to session"
complete -c kak -o f -x -d "run in filter mode"
complete -c kak -o i -x -d "edit files in-place, saving backups with the specified extension"
complete -c kak -o q -d "run in quiet mode"
complete -c kak -o ui -x -a "terminal" -d "terminal"
complete -c kak -o ui -x -a "dummy" -d "dummy"
complete -c kak -o ui -x -a "json" -d "json"
complete -c kak -o ui -x -d "set the type of user interface"
complete -c kak -o ro -d "run in read-only mode"
complete -c kak -o l -d "list sessions"
complete -c kak -o clear -d "clear dead sessions"
complete -c kak -o debug -x -d "set debug flags"
complete -c kak -o help -d "show this help"
complete -c kak -o version -d "show version"
