complete -c kak -s p -l pick-command -x -a "(__fish_complete_command)" -d "Specifies the command to run on unchanged items"
complete -c kak -s m -l map-command -x -a "(__fish_complete_command)" -d "Specifies the command to run on modified items"
complete -c kak -s d -l drop-command -x -a "(__fish_complete_command)" -d "Specifies the command to run on deleted items"
complete -c kak -s P -l pick-shell-script -x -a "(__fish_complete_command)" -d "Specifies the shell script to run on unchanged items"
complete -c kak -s M -l map-shell-script -x -a "(__fish_complete_command)" -d "Specifies the shell script to run on modified items"
complete -c kak -s D -l drop-shell-script -x -a "(__fish_complete_command)" -d "Specifies the shell script to run on deleted items"
complete -c kak -s e -l editor -x -a "(__fish_complete_command)" -d "Specifies the editor to use"
complete -c kak -s f -l filter -x -a "(__fish_complete_command)" -d "Adds a filter (repeatable)"
complete -c kak -s E -l no-edit -d "Do not open editor"
complete -c kak -l no-pick -d "Do not pick items"
complete -c kak -l no-map -d "Do not map items"
complete -c kak -l no-drop -d "Do not drop items"
complete -c kak -s h -l help -d "Show this help"
complete -c kak -s V -l version -d "Show version"
