# name: kakoune_list_friendly_client_names
# version: 0.1.0
# description: This script provides the functionality to list friendly client names.
# authors: ["Mathieu Ablasou <taupiqueur.kanto@gmail.com>"]
# kakoune: 2023-12-12
# license: MIT
# dependencies: []
# doc: yes
# tests: no
decl -docstring "
friendly_client_names: [...]
" str-list friendly_client_names \
  "bulbizarre" \
  "herbizarre" \
  "florizarre" \
  "salameche" \
  "reptincel" \
  "dracaufeu" \
  "carapuce" \
  "carabaffe" \
  "tortank" \
  "chenipan" \
  "chrysacier" \
  "papilusion" \
  "aspicot" \
  "coconfort" \
  "dardargnan" \
  "roucool" \
  "roucoups" \
  "roucarnage" \
  "rattata" \
  "rattatac" \
  "piafabec" \
  "rapasdepic" \
  "abo" \
  "arbok" \
  "pikachu" \
  "raichu" \
  "sabelette" \
  "sablaireau" \
  "nidoran" \
  "nidorina" \
  "nidoqueen" \
  "nidoran" \
  "nidorino" \
  "nidoking" \
  "melofee" \
  "melodelfe" \
  "goupix" \
  "feunard" \
  "rondoudou" \
  "grodoudou" \
  "nosferapti" \
  "nosferalto" \
  "mystherbe" \
  "ortide" \
  "rafflesia" \
  "paras" \
  "parasect" \
  "mimitoss" \
  "aeromite" \
  "taupiqueur" \
  "triopikeur" \
  "miaouss" \
  "persian" \
  "psykokwak" \
  "akwakwak" \
  "ferosinge" \
  "colossinge" \
  "caninos" \
  "arcanin" \
  "ptitard" \
  "tetarte" \
  "tartard" \
  "abra" \
  "kadabra" \
  "alakazam" \
  "machoc" \
  "machopeur" \
  "mackogneur" \
  "chetiflor" \
  "boustiflor" \
  "empiflor" \
  "tentacool" \
  "tentacruel" \
  "racaillou" \
  "gravalanch" \
  "grolem" \
  "ponyta" \
  "galopa" \
  "ramoloss" \
  "flagadoss" \
  "magneti" \
  "magneton" \
  "canarticho" \
  "doduo" \
  "dodrio" \
  "otaria" \
  "lamantine" \
  "tadmorv" \
  "grotadmorv" \
  "kokiyas" \
  "crustabri" \
  "fantominus" \
  "spectrum" \
  "ectoplasma" \
  "onix" \
  "soporifik" \
  "hypnomade" \
  "krabby" \
  "krabboss" \
  "voltorbe" \
  "electrode" \
  "noeunoeuf" \
  "noadkoko" \
  "osselait" \
  "ossatueur" \
  "kicklee" \
  "tygnon" \
  "excelangue" \
  "smogo" \
  "smogogo" \
  "rhinocorne" \
  "rhinoferos" \
  "leveinard" \
  "saquedeneu" \
  "kangourex" \
  "hypotrempe" \
  "hypocean" \
  "poissirene" \
  "poissoroy" \
  "stari" \
  "staross" \
  "m_mime" \
  "insecateur" \
  "lippoutou" \
  "elektek" \
  "magmar" \
  "scarabrute" \
  "tauros" \
  "magicarpe" \
  "leviator" \
  "lokhlass" \
  "metamorph" \
  "evoli" \
  "aquali" \
  "voltali" \
  "pyroli" \
  "porygon" \
  "amonita" \
  "amonistar" \
  "kabuto" \
  "kabutops" \
  "ptera" \
  "ronflex" \
  "artikodin" \
  "electhor" \
  "sulfura" \
  "minidraco" \
  "draco" \
  "dracolosse" \
  "mewtwo" \
  "mew" \
  "germignon" \
  "macronium" \
  "meganium" \
  "hericendre" \
  "feurisson" \
  "typhlosion" \
  "kaiminus" \
  "crocrodil" \
  "aligatueur" \
  "fouinette" \
  "fouinar" \
  "hoothoot" \
  "noarfang" \
  "coxy" \
  "coxyclaque" \
  "mimigal" \
  "migalos" \
  "nostenfer" \
  "loupio" \
  "lanturn" \
  "pichu" \
  "melo" \
  "toudoudou" \
  "togepi" \
  "togetic" \
  "natu" \
  "xatu" \
  "wattouat" \
  "lainergie" \
  "pharamp" \
  "joliflor" \
  "marill" \
  "azumarill" \
  "simularbre" \
  "tarpaud" \
  "granivol" \
  "floravol" \
  "cotovol" \
  "capumain" \
  "tournegrin" \
  "heliatronc" \
  "yanma" \
  "axoloto" \
  "maraiste" \
  "mentali" \
  "noctali" \
  "cornebre" \
  "roigada" \
  "feuforeve" \
  "zarbi" \
  "qulbutoke" \
  "girafarig" \
  "pomdepik" \
  "foretress" \
  "insolourdo" \
  "scorplane" \
  "steelix" \
  "snubbull" \
  "granbull" \
  "qwilfish" \
  "cizayox" \
  "caratroc" \
  "scarhino" \
  "farfuret" \
  "teddiursa" \
  "ursaring" \
  "limagma" \
  "volcaropod" \
  "marcacrin" \
  "cochignon" \
  "corayon" \
  "remoraid" \
  "octillery" \
  "cadoizo" \
  "demanta" \
  "airmure" \
  "malosse" \
  "demolosse" \
  "hyporoi" \
  "phanpy" \
  "donphan" \
  "porygon2" \
  "cerfrousse" \
  "queulorior" \
  "debugant" \
  "kapoera" \
  "lippouti" \
  "elekid" \
  "magby" \
  "ecremeuh" \
  "leuphorie" \
  "raikou" \
  "entei" \
  "suicune" \
  "embrylex" \
  "ymphect" \
  "tyranocif" \
  "lugia" \
  "ho_oh" \
  "celebi" \

def -docstring "
usage: list-friendly-client-names
config_options: [""friendly_client_names""]
" list-friendly-client-names %{
  new-buffer "*friendly_client_names*"
  eval -save-regs """" %{
    reg """" %opt{friendly_client_names}
    exec "<a-R>i<ret><esc>ggd"
  }
}

def -hidden rename_client_to_selected_friendly_client_name %{
  eval -draft %{
    select_friendly_client_name_entries 1
    eval -client %val{client} -verbatim rename-client -- %val{selection}
  }
}

def -hidden select_friendly_client_name_entries -params 1 %{
  exec "x<a-s>%arg{1}s\A(.+?)\n\z<ret>"
}
