# Nushell
# https://nushell.sh

# Paths
path = [
  '/home/taupiqueur/configuration/bin',
  '/home/taupiqueur/configuration/local/bin',
  '/home/taupiqueur/.local/share/crystal/releases/latest/bin',
  '/home/taupiqueur/.bin',
  '/home/taupiqueur/.local/bin',
  '/home/taupiqueur/.gem/ruby/2.7.0/bin',
  '/home/taupiqueur/.cargo/bin',
  '/home/taupiqueur/.cabal/bin',
  '/home/taupiqueur/go/bin',
  'node_modules/.bin',
  '/home/taupiqueur/.npm-packages/bin',

  # Tools
  '/home/taupiqueur/projects/git-churn/bin',
  '/home/taupiqueur/projects/git-gc-all-ferocious/bin',
  '/home/taupiqueur/projects/kakoune/src',
  '/home/taupiqueur/projects/pager.kak/bin',
  '/home/taupiqueur/repositories/github.com/Blacksmoke16/oq/bin'
]

# Options
skip_welcome_message = true

# Starship
# https://starship.rs
prompt = 'starship prompt'

# Startup
startup = [
  '''
  # Aliases
  alias @ = fork
  alias p = echo
  alias _ = rm -rf
  alias md = mkdir

  # NixOS
  # https://nixos.org
  alias ns = nix-shell --command nu
  alias nrs = nix-shell --command nu --packages pkg-config rustup rustc cargo
  alias ncr = nix-shell --command nu --packages pcre libevent libyaml
  alias nrb = nix-shell --command nu --packages rubyPackages_2_7.railties

  # Sleep
  alias z = systemctl suspend
  alias zz = swaymsg exit
  alias zzz = shutdown now

  # SSH
  def ssh! [] {
    rm -rf ~/.cache/ssh/sessions
    mkdir ~/.cache/ssh/sessions
  }

  # Keyboard
  alias kbd = swaymsg input 1:1:AT_Translated_Set_2_keyboard events toggle

  # procs
  # https://github.com/dalance/procs
  alias ps = procs

  # rsync
  # https://rsync.samba.org
  alias cp = rsync --archive --compress --hard-links --info=progress2 --delete

  # rm
  alias rm = rm -rf --trash
  alias rm! = rm -rf ~/.local/share/Trash

  # bat
  # https://github.com/sharkdp/bat
  alias cat = bat

  # fd
  # https://github.com/sharkdp/fd
  alias find = fd

  # ripgrep
  # https://github.com/BurntSushi/ripgrep
  alias grep = rg

  # curl
  # https://curl.haxx.se
  alias curl = curl -sSL

  # archiver
  # https://github.com/mholt/archiver
  alias x = arc unarchive

  # https://github.com/bugaevc/wl-clipboard
  alias yk = wl-copy

  # wf-recorder
  # https://github.com/ammen99/wf-recorder
  def rec [] {
    wf-recorder -f $(new-file '' .mkv)
  }

  # XWayland
  def x11 [] {
    let-env GDK_BACKEND = x11
    let-env QT_QPA_PLATFORM = xcb
  }

  # tab
  # https://github.com/austinjones/tab-rs
  alias t = tab
  alias t~ = tab home
  alias tl = tab --list
  alias tw = tab --close
  alias tW = tab --shutdown

  # Pueue
  # https://github.com/Nukesor/pueue
  alias q = pueue
  alias Q = fork pueued
  alias qj = pueue parallel
  alias qa = pueue add
  alias qi = pueue status

  alias ql = pueue log
  alias qL = pueue follow

  alias qp = pueue pause
  alias qP = pueue start

  alias q5 = pueue clean

  alias qw = pueue kill
  alias qW = pueue shutdown

  # kakoune.cr
  # https://github.com/alexherbo2/kakoune.cr
  alias k = kcr edit
  alias K = kcr-fzf-shell
  alias KK = kcr-fzf-shell --working-directory .
  alias ks = kcr shell --session
  alias kl = kcr list
  alias a = kcr attach
  alias : = kcr send
  alias :br = kcr-fzf-shell --working-directory . broot
  alias :cat = kcr cat --raw

  alias val = kcr get --value
  alias opt = kcr get --option
  alias reg = kcr get --register

  # Git
  # https://git-scm.com
  alias g = git

  # lazygit
  # https://github.com/jesseduffield/lazygit
  alias G = lazygit

  # GitHub CLI
  # https://cli.github.com
  alias gist = gh gist create --web
  alias gv = gh repo view --web

  def gc [repository] {
    gh repo clone $repository `~/repositories/github.com/{{$repository}}`
  }

  # Broot
  # https://dystroy.org/broot/
  def br [] {
    let path = $(broot --out /dev/stdout | str trim)
    let is_empty = $(= $path | empty?)
    if $is_empty {} {
      cd $path
    }
  }

  # Broot – Replace `ls` (and its clones)
  # https://dystroy.org/broot#replace-ls-and-its-clones
  alias l = broot --sizes --dates --permissions
  alias la = broot --sizes --dates --permissions --hidden

  # Batch
  # https://github.com/alexherbo2/batch
  alias batch = batch --editor kak
  alias rn = batch --editor kak --map 'rename "$1" "$2"'
  alias rl = batch --editor kak --map 'relink "$1" "$2"'
  alias cv = batch --editor kak --map 'convert "$1" "$2"'

  # Chronic
  # https://github.com/alexherbo2/chronic
  alias cr = chronic

  # File manager
  alias d = fork dolphin

  # Web browser
  alias b = fork chromium

  # mpv
  # https://mpv.io
  alias m = mpv

  # mpv – image
  alias mi = mpv -config-dir ~/.config/mpv/profiles/image

  # mpv – audio
  alias ma = mpv -config-dir ~/.config/mpv/profiles/audio

  # mpv – filter
  alias mx = mpv -config-dir ~/.config/mpv/profiles/filter

  # https://ytdl-org.github.io/youtube-dl/
  alias y = youtube-dl

  # Pandoc
  # https://pandoc.org
  alias pandoc = pandoc --defaults ~/.config/pandoc/config.yml

  # Password
  # https://github.com/alexherbo2/password
  alias pc = password create
  alias pg = password get
  alias pe = password edit
  def pm [] {
    password get $(password menu | fzf --header='Select a password to copy' --prompt='(p)>') |
    wl-copy
  }

  # Ruby on Rails
  # https://rubyonrails.org
  alias r = rails
  alias rr = rails-routes
  '''
]

# Environment variables
[env]

# Current shell
# Useful to open a new terminal in Kakoune.
SHELL = '/run/current-system/sw/bin/nu'

# Manual paths
MANPATH = '/home/taupiqueur/.npm-packages/share/man:'

# Applications
EDITOR = 'kcr edit'
BROWSER = 'chromium'
KAKOUNE_POSIX_SHELL = '/run/current-system/sw/bin/dash'
MANPAGER = 'kak-man-pager'

# ripgrep
RIPGREP_CONFIG_PATH = '/home/taupiqueur/.config/ripgrep/rc'

# fzf
FZF_DEFAULT_OPTS = '--multi --layout=reverse --preview-window=down:60%'
