# Nushell
# https://nushell.sh

# Paths
path = [
  '/home/taupiqueur/configuration/bin',
  '/home/taupiqueur/configuration/local/bin',
  '/home/taupiqueur/.local/bin',

  # Projects
  # Krabby – https://krabby.netlify.app
  '/home/taupiqueur/projects/krabby/bin',

  # kakoune.cr – https://github.com/alexherbo2/kakoune.cr
  '/home/taupiqueur/projects/kakoune.cr/bin',
  '/home/taupiqueur/projects/kakoune.cr/share/kcr/commands/edit',
  '/home/taupiqueur/projects/kakoune.cr/share/kcr/commands/fzf',

  # Batch – https://github.com/alexherbo2/batch
  '/home/taupiqueur/projects/batch/bin',
  '/home/taupiqueur/projects/batch/share/batch/scripts',
  '/home/taupiqueur/projects/batch.kak/bin',

  # Chronic – https://github.com/alexherbo2/chronic
  '/home/taupiqueur/projects/chronic/bin',

  # Tools – https://github.com/alexherbo2/{tool}
  '/home/taupiqueur/projects/snippets/bin',
  '/home/taupiqueur/projects/launcher/bin',
  '/home/taupiqueur/projects/password/bin',

  # Tools – https://github.com/alexherbo2/{tool}
  '/home/taupiqueur/projects/git-tools/bin',
  '/home/taupiqueur/projects/ffmpeg-tools/bin',
  '/home/taupiqueur/projects/sway-tools/bin',

  # Tools
  '/home/taupiqueur/repositories/github.com/facundoolano/rpg-cli/target/release',
  '/home/taupiqueur/repositories/github.com/mawww/kakoune/src',
  '/home/taupiqueur/repositories/github.com/kak-lsp/kak-lsp/target/release',
  '/home/taupiqueur/repositories/github.com/alacritty/alacritty/target/release',
  '/home/taupiqueur/repositories/github.com/nushell/nushell/target/release',
  '/home/taupiqueur/repositories/github.com/Canop/broot/target/release',
  '/home/taupiqueur/repositories/github.com/sayanarijit/xplr/target/release',
  '/home/taupiqueur/repositories/github.com/topisani/sidetree/target/release',
  '/home/taupiqueur/repositories/github.com/zellij-org/zellij/target/release',
  '/home/taupiqueur/repositories/github.com/austinjones/tab-rs/target/release',
  '/home/taupiqueur/repositories/github.com/Nukesor/pueue/target/release',
  '/home/taupiqueur/repositories/github.com/extrawurst/gitui/target/release',
  '/home/taupiqueur/repositories/github.com/Luminarys/synapse/target/release',
  '/home/taupiqueur/repositories/github.com/Blacksmoke16/oq/bin',

  # Packages
  '/home/taupiqueur/.cargo/bin',
  '/home/taupiqueur/.gem/ruby/3.0.0/bin',
  'node_modules/.bin',
  '/home/taupiqueur/.npm-packages/bin',
  '/home/taupiqueur/.yarn/bin',
  '/home/taupiqueur/go/bin',
  '/home/taupiqueur/.cabal/bin'
]

# Options
skip_welcome_message = true

# Starship
# https://starship.rs
prompt = 'starship prompt'

# Startup
startup = [
  '''
  # TTY settings
  if $(= linux != $nu.env.TERM) {} {
    # Color scheme
    # https://draculatheme.com/tty
    sh ~/repositories/github.com/dracula/tty/dracula-tty.sh

    # Fonts
    # /run/current-system/sw/share/consolefonts
    setfont Lat2-Terminus16
  }

  # Aliases
  alias @ = fork
  alias p = echo
  alias _ = rm -rf
  alias md = mkdir

  # rpg-cli — your filesystem as a dungeon!
  # https://github.com/facundoolano/rpg-cli
  def rpg [...rest] {
    rpg-cli $rest
    cd $(rpg-cli --pwd | str trim)
  }

  # NixOS
  # https://nixos.org
  alias nix-update = sudo nixos-rebuild switch
  alias nix-upgrade = sudo nixos-rebuild switch --upgrade --keep-going --fallback
  alias nix-gc = sudo nix-collect-garbage --delete-old

  # Shell
  alias na = nix-shell-attr
  alias ns = nix-shell --command nu
  alias np = nix-shell --command nu --packages

  # Compiling
  alias nix-cargo = nix-shell --run 'cargo build --release' --packages pkg-config rustup rustc cargo openssl
  alias nix-shards = shards build --release --production

  # KDE
  # https://kde.org
  alias kcm = kcmshell5-fzf

  # Sleep
  alias z = sudo systemctl suspend
  alias zz = swaymsg exit
  alias zzz = sudo shutdown now

  # SSH
  def ssh! [] {
    rm -rf ~/.cache/ssh/sessions
    mkdir ~/.cache/ssh/sessions
  }

  # nginx
  # https://nginx.org
  alias nginx = sudo nginx -c /etc/nginx/nginx.conf

  # Wallpapers
  def bg [...rest] {
    swaymsg output '*' bg $rest fill
  }

  # Keyboard
  alias fr = swaymsg input type:keyboard xkb_file ~/repositories/github.com/fabi1cazenave/qwerty-lafayette/dist/qwerty-l.xkb
  alias kbd = swaymsg input 1:1:AT_Translated_Set_2_keyboard events toggle

  # procs
  # https://github.com/dalance/procs
  alias ps = procs

  # htop
  # https://htop.dev
  alias top = htop

  # rsync
  # https://rsync.samba.org
  alias cp = rsync --archive --compress --hard-links --info=progress2 --delete

  # rm
  alias rm = rm -rf --trash
  alias rm! = rm -rf ~/.local/share/Trash

  # bat
  # https://github.com/sharkdp/bat
  alias cat = bat

  # fd
  # https://github.com/sharkdp/fd
  alias find = fd

  # ripgrep
  # https://github.com/BurntSushi/ripgrep
  alias grep = rg

  # curl
  # https://curl.haxx.se
  alias curl = curl -sSL

  # archiver
  # https://github.com/mholt/archiver
  alias x = arc unarchive

  # https://github.com/bugaevc/wl-clipboard
  alias yk = wl-copy

  # wf-recorder
  # https://github.com/ammen99/wf-recorder
  def rec [] {
    wf-recorder -f $(new-file '' .mkv)
  }

  # XWayland
  def x11 [] {
    let-env GDK_BACKEND = x11
    let-env QT_QPA_PLATFORM = xcb
  }

  # Zellij
  # https://zellij.dev
  alias mux = zellij

  # tab
  # https://github.com/austinjones/tab-rs
  alias t = tab
  alias t~ = tab home
  alias tl = tab --list
  alias tw = tab --close
  alias tW = tab --shutdown

  # Pueue
  # https://github.com/Nukesor/pueue
  alias q = pueue
  alias Q = fork pueued
  alias qj = pueue parallel
  alias qa = pueue add
  alias qi = pueue status
  alias qI = pueue clean

  alias ql = pueue-fzf log
  alias qL = pueue-fzf follow

  alias qp = pueue-fzf pause
  alias qP = pueue-fzf start

  alias qw = pueue-fzf kill
  alias qW = pueue shutdown

  # synapse
  # https://synapse-bt.org
  alias s = sycli
  alias S = pueue add synapse
  alias sa = sycli add
  alias si = sycli status
  alias sl = sycli list
  alias sp = sycli-fzf pause
  alias sP = sycli-fzf resume
  alias sw = sycli-fzf del --files
  alias sW = pkill synapse

  # The Lounge
  # https://thelounge.chat
  alias irc = pueue add thelounge start

  # kakoune.cr
  # https://github.com/alexherbo2/kakoune.cr
  alias k = kcr edit
  alias K = kcr-fzf-shell
  alias KK = kcr-fzf-shell --working-directory .
  alias ks = kcr shell --session
  alias kl = kcr list
  alias a = kcr attach
  alias : = kcr send
  alias :cd = kcr send cd "$PWD"
  def cd: [] { cd $(kcr get --raw --shell pwd | str trim) }
  alias :st = kcr-fzf-shell --working-directory . sidetree
  alias :cat = kcr cat --raw

  alias val = kcr get --value
  alias opt = kcr get --option
  alias reg = kcr get --register

  # Git
  # https://git-scm.com
  alias g = git

  # Change the working directory to the Git root:
  def @cd [] {
    cd $(git rev-parse --show-toplevel | str trim)
  }

  # gitui
  # https://github.com/extrawurst/gitui
  alias G = gitui

  # GitHub CLI
  # https://cli.github.com
  alias gist = gh gist create --web
  alias gv = gh repo view --web

  def gc [repository] {
    gh repo clone $repository `~/repositories/github.com/{{$repository}}`
  }

  # Broot
  # https://dystroy.org/broot/
  def br [...rest] {
    let path = $(broot --out /dev/stdout $rest | str trim)
    let is_empty = $(= $path | empty?)
    if $is_empty {} {
      cd $path
    }
  }
  alias . = br .

  # exa
  # https://the.exa.website
  alias l = exa --icons
  alias la = exa --icons --all
  alias ll = exa --icons --git --long
  alias lla = exa --icons --git --long --all
  alias T = exa --tree
  alias ta = exa --tree --all

  # Batch
  # https://github.com/alexherbo2/batch
  alias batch = batch --editor kak
  alias rn = batch --editor kak --map 'rename "$1" "$2"'
  alias rl = batch --editor kak --map 'relink "$1" "$2"'
  alias cv = batch --editor kak --map 'convert "$1" "$2"'

  # Chronic
  # https://github.com/alexherbo2/chronic
  alias cr = chronic

  # File manager
  alias d = fork dolphin

  # Web browser
  alias b = fork chromium

  # mpv
  # https://mpv.io
  alias m = mpv
  alias ms = mpv -shuffle

  # mpv – image
  alias mi = mpv -config-dir ~/.config/mpv/profiles/image

  # mpv – audio
  alias ma = mpv -config-dir ~/.config/mpv/profiles/audio

  # mpv – filter
  alias mx = mpv -config-dir ~/.config/mpv/profiles/filter

  # https://ytdl-org.github.io/youtube-dl/
  alias y = youtube-dl

  # Pandoc
  # https://pandoc.org
  alias pandoc = pandoc --defaults ~/.config/pandoc/config.yml

  # Password
  # https://github.com/alexherbo2/password
  alias pc = password create
  alias pg = password get
  alias pe = password edit
  def pm [] {
    password menu | fzf --header='Select a password to copy' --prompt='(p)>' |
    xargs password get -- |
    wl-copy
  }

  # Ruby on Rails
  # https://rubyonrails.org
  alias r = rails
  alias rr = rails-routes
  '''
]

# Environment variables
[env]

# Desktop environment
# https://kde.org
#
# Note: KDE apps need this for non-KDE desktops.
XDG_CURRENT_DESKTOP = 'kde'

# Current shell
# Useful to open a new terminal in Kakoune.
# Use the latest version of Nushell.
# SHELL = '/home/taupiqueur/repositories/github.com/nushell/nushell/target/release/nu'

# Manual paths
MANPATH = '/home/taupiqueur/.npm-packages/share/man:'

# Applications
EDITOR = 'kcr edit'
BROWSER = 'chromium'
KAKOUNE_POSIX_SHELL = '/run/current-system/sw/bin/dash'
MANPAGER = '''sh -c 'col -b -x | kak -e "set-option buffer filetype man"' --'''

# ripgrep
RIPGREP_CONFIG_PATH = '/home/taupiqueur/.config/ripgrep/rc'

# fzf
FZF_DEFAULT_OPTS = '--multi --layout=reverse --preview-window=down:60%'
