#!/bin/sh

# limelight
# https://github.com/koekeishiya/limelight

# Preamble
alias set='limelight --message config'

# Color palette
green=0xff50fa7b # Dracula
white=0xffeaeaea # macOS

# Options
set width 4
set radius 0
set placement interior
set active_color $green
set normal_color $white
