# Alacritty
# https://alacritty.org

general.import = [
  '~/.config/alacritty/colors/macos_light_low_contrast.toml'
]

# Appearance -------------------------------------------------------------------

font.normal.family = 'SF Mono'
font.normal.style = 'Regular'
font.size = 11.25

selection.save_to_clipboard = true

window.option_as_alt = 'Both'

cursor.style.shape = 'Beam'
cursor.style.blinking = 'On'
cursor.blink_timeout = 0
cursor.unfocused_hollow = false

[bell.command]
program = 'osascript'
args = ['-e', 'beep']

# Key bindings -----------------------------------------------------------------

# macOS
[[keyboard.bindings]]
key = 'n'
mods = 'Command'
action = 'CreateNewWindow'

[[keyboard.bindings]]
key = 'p'
mods = 'Command'
action = 'SpawnNewInstance'

[[keyboard.bindings]]
key = '['
mods = 'Command'
action = 'SelectPreviousTab'

[[keyboard.bindings]]
key = ']'
mods = 'Command'
action = 'SelectNextTab'

# Linux
[[keyboard.bindings]]
key = 'n'
mods = 'Control|Shift'
action = 'CreateNewWindow'

[[keyboard.bindings]]
key = 'p'
mods = 'Control|Shift'
action = 'SpawnNewInstance'

[[keyboard.bindings]]
key = 'Tab'
mods = 'Control|Shift'
action = 'SelectPreviousTab'

[[keyboard.bindings]]
key = 'Tab'
mods = 'Control'
action = 'SelectNextTab'

[[keyboard.bindings]]
key = 'PageUp'
mods = 'Control'
action = 'SelectPreviousTab'

[[keyboard.bindings]]
key = 'PageDown'
mods = 'Control'
action = 'SelectNextTab'
