# Default flags
# "g" ⇒ --show-git-info
# "i" ⇒ --show-gitignored
default_flags = "gi"

# Navigation ───────────────────────────────────────────────────────────────────

[[verbs]]
key = "alt-l"
execution = ":open_stay"

[[verbs]]
key = "alt-h"
execution = ":back"

[[verbs]]
key = "alt-j"
execution = ":line_down"

[[verbs]]
key = "alt-k"
execution = ":line_up"

# Commands ─────────────────────────────────────────────────────────────────────

# Kakoune
# https://kakoune.org
[[verbs]]
invocation = "edit"
shortcut = "e"
execution = "kak {file}"
leave_broot = false

# archiver
# https://github.com/mholt/archiver
[[verbs]]
invocation = "extract"
shortcut = "x"
execution = "arc unarchive {file}"
leave_broot = false

# mpv
# https://mpv.io
[[verbs]]
invocation = "mpv"
shortcut = "m"
execution = "mpv -really-quiet {directory}"
leave_broot = false

# bat
# https://github.com/sharkdp/bat
[[verbs]]
invocation = "view"
shortcut = "v"
execution = "bat {file}"
leave_broot = false
