# Broot
# https://dystroy.org/broot/

# Options ──────────────────────────────────────────────────────────────────────

# Default flags
# [g] ⇒ --show-git-info
# [i] ⇒ --show-gitignored
default_flags = 'gi'

# Commands ─────────────────────────────────────────────────────────────────────

# Quit
[[verbs]]
invocation = 'quit'
shortcut = 'q'
execution = ':quit'

# Toggle hidden files
[[verbs]]
invocation = 'toggle hidden'
shortcut = '.'
execution = ':toggle_hidden'

# Toggle sizes
[[verbs]]
invocation = 'toggle sizes'
shortcut = 'i'
execution = ':toggle_sizes'

# Open a terminal here
[[verbs]]
invocation = 'terminal'
shortcut = 't'
execution = '$SHELL'
set_working_dir = true
leave_broot = false

# Move to home
[[verbs]]
invocation = 'home'
shortcut = '~'
execution = ':focus ~'
leave_broot = false

# bat
# https://github.com/sharkdp/bat
[[verbs]]
invocation = 'view'
shortcut = 'v'
execution = 'bat {file}'
leave_broot = false

# Kakoune
# https://kakoune.org
[[verbs]]
invocation = 'edit'
shortcut = 'e'
execution = '$EDITOR +{line} {file}'
leave_broot = false

# Create new text files.
[[verbs]]
invocation = 'create {subpath}'
shortcut = 'c'
execution = '$EDITOR {directory}/{subpath}'
leave_broot = false

# archiver
# https://github.com/mholt/archiver
[[verbs]]
invocation = 'extract'
shortcut = 'x'
execution = 'arc unarchive {file}'
set_working_dir = true
leave_broot = false

# mpv
# https://mpv.io
[[verbs]]
invocation = 'mpv'
shortcut = 'm'
execution = 'mpv --really-quiet {file}'
leave_broot = false
