[[verbs]]
name = "view"
invocation = "view"
shortcut = "v"
execution = "bat {file}"

[[verbs]]
key = "alt-l"
execution = ":open_stay"

[[verbs]]
key = "alt-h"
execution = ":back"

[[verbs]]
key = "alt-j"
execution = ":line_down"

[[verbs]]
key = "alt-k"
execution = ":line_up"
