# Broot
# https://dystroy.org/broot/

# Options ──────────────────────────────────────────────────────────────────────

modal = true

# Default flags
# [g] ⇒ --show-git-info
# [i] ⇒ --show-gitignored
default_flags = 'gi'

# Commands ─────────────────────────────────────────────────────────────────────

# Toggle hidden files
[[verbs]]
key = '.'
execution = ':toggle_hidden'

# kakoune.cr
# https://github.com/alexherbo2/kakoune.cr
[[verbs]]
key = 'e'
invocation = 'edit'
shortcut = 'e'
execution = 'kcr edit +{line} {file}'
leave_broot = false

# archiver
# https://github.com/mholt/archiver
[[verbs]]
key = 'x'
invocation = 'extract'
shortcut = 'x'
execution = 'arc unarchive {file}'
leave_broot = false

# mpv
# https://mpv.io
[[verbs]]
key = 'm'
invocation = 'mpv'
shortcut = 'm'
execution = 'mpv -really-quiet {file}'
leave_broot = false
