map -docstring 'extend cursor file start' global goto 'G' '<esc>Gg'
map -docstring 'extend cursor file end' global goto 'E' '<esc>Ge'
map -docstring 'move cursor last line' global goto 'e' '<esc>gj'
map -docstring 'extend cursor line content start' global goto 'I' '<esc>Gi'
map -docstring 'extend cursor line start' global goto 'H' '<esc>Gh'
map -docstring 'extend cursor line end' global goto 'L' '<esc>Gl'
map -docstring 'extend cursor line start' global goto 'G' '<esc>Gg'
map -docstring 'extend cursor window top' global goto 'T' '<esc>Gt'
map -docstring 'extend cursor window center' global goto 'C' '<esc>Gc'
map -docstring 'extend cursor window bottom' global goto 'B' '<esc>Gb'
map -docstring 'move cursor line down' global goto 'j' '<esc>j'
map -docstring 'move cursor line up' global goto 'k' '<esc>k'
map -docstring 'extend cursor line down' global goto 'J' '<esc>J'
map -docstring 'extend cursor line up' global goto 'K' '<esc>K'
map -docstring 'enter jump mode (select mode: replace)' global goto w '<esc>:enter_jump_mode_with_replace_select_mode<ret>'
map -docstring 'enter jump mode (select mode: extend)' global goto W '<esc>:enter_jump_mode_with_extend_select_mode<ret>'
map -docstring 'enter jump mode (select mode: append)' global goto <a-w> '<esc>:enter_jump_mode_with_append_select_mode<ret>'
