map -docstring 'move cursor line down' global goto 'j' '<esc>j'
map -docstring 'move cursor line up' global goto 'k' '<esc>k'
map -docstring 'extend cursor line down' global goto 'J' '<esc>J'
map -docstring 'extend cursor line up' global goto 'K' '<esc>K'
map -docstring 'enter jump mode (select mode: replace)' global goto w '<esc>:enter_jump_mode_with_replace_select_mode<ret>'
map -docstring 'enter jump mode (select mode: extend)' global goto W '<esc>:enter_jump_mode_with_extend_select_mode<ret>'
map -docstring 'enter jump mode (select mode: append)' global goto <a-w> '<esc>:enter_jump_mode_with_append_select_mode<ret>'
