# Helix
# https://helix-editor.com
# https://docs.helix-editor.com/keymap.html
# https://docs.helix-editor.com/commands.html
# https://docs.helix-editor.com/configuration.html
# https://github.com/helix-editor/helix/blob/master/helix-term/src/keymap/default.rs
# https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs
# https://github.com/helix-editor/helix/blob/master/helix-term/src/commands/typed.rs
# https://github.com/helix-editor/helix/blob/master/helix-view/src/editor.rs

# Appearance -------------------------------------------------------------------

theme = 'onelight'

[editor]
rulers = [81]
line-number = 'relative'
color-modes = true

[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.whitespace]
render = 'all'
characters = { newline = '¬' }

[editor.file-picker]
hidden = false

# Key bindings -----------------------------------------------------------------

# Kakoune keyboard shortcuts
# https://kakoune.org

# VS Code keyboard shortcuts
# https://code.visualstudio.com/docs/getstarted/keybindings#_default-keyboard-shortcuts

# Normal mode ------------------------------------------------------------------

# Reference:
# https://github.com/mawww/kakoune/blob/master/src/normal.cc

[keys.normal]
ret = 'command_mode'

H = 'extend_char_left'
J = 'extend_line_down'
K = 'extend_line_up'
L = 'extend_char_right'

f = ['ensure_selections_forward', 'extend_next_char']
t = ['ensure_selections_forward', 'extend_till_char']
F = ['ensure_selections_forward', 'flip_selections', 'extend_prev_char']
T = ['ensure_selections_forward', 'flip_selections', 'extend_till_prev_char']

q = 'surround_add'
Q = ['ensure_selections_forward', 'extend_char_right', 'delete_char_forward', 'flip_selections', 'delete_char_backward', 'ensure_selections_forward']

W = 'extend_next_word_start'
E = 'extend_next_word_end'
B = 'extend_prev_word_start'

A-W = 'extend_next_long_word_start'
A-E = 'extend_next_long_word_end'
A-B = 'extend_prev_long_word_start'

A-h = ['ensure_selections_forward', 'flip_selections', 'extend_to_line_start']
A-l = ['ensure_selections_forward', 'extend_to_line_end']

G.e = ['select_mode', 'ensure_selections_forward', 'goto_file_end', 'exit_select_mode']
m.x = ['extend_to_line_bounds', 'trim_selections']

v = 'select_textobject_inner'
V = 'select_textobject_around'

'{' = ['ensure_selections_forward', 'flip_selections', 'select_mode', 'goto_prev_paragraph', 'exit_select_mode']
'}' = ['ensure_selections_forward', 'select_mode', 'goto_next_paragraph', 'exit_select_mode']

A-j = 'join_selections'
A-k = 'keep_selections'

minus = ['ensure_selections_forward', 'extend_char_right', 'extend_char_left']

'@' = 'record_macro'

X = ['extend_to_line_bounds', 'ensure_selections_forward', 'flip_selections']
D = ['ensure_selections_forward', 'extend_to_line_bounds', 'extend_char_right', 'extend_char_left', 'delete_selection', 'add_newline_below', 'move_line_down', 'replace_with_yanked']
Y = ['ensure_selections_forward', 'extend_to_line_bounds', 'extend_char_right', 'extend_char_left', 'delete_selection', 'move_line_up', 'add_newline_above', 'move_line_up', 'replace_with_yanked']

'#' = 'toggle_comments'

[keys.normal.space]
space = 'select_mode'
o = 'add_newline_below'
O = 'add_newline_above'
'@' = 'record_macro'

# Format date to 2006-01-02 Mon.
D = ':pipe date -d "$(cat)" "+%F %a" | tr -d "\\n"'

[keys.normal.space.w]
o = 'hsplit'
O = 'vsplit'
c = 'wclose'
C = 'wonly'

# Insert mode ------------------------------------------------------------------

# Reference:
# https://github.com/mawww/kakoune/blob/master/src/input_handler.cc

[keys.insert]
# Insert date (2006-01-02 Mon 15:04).
C-d = ':insert-output date "+%F %a" | tr -d "\\n"'

[keys.insert.C-space]
'#' = ['collapse_selection', ':insert-output printf 0', 'move_char_left', 'yank_joined_to_clipboard', ':new', 'replace_selections_with_clipboard', ':pipe awk "{ print NR - 1 }"', 'split_selection_on_newline', 'yank', ':buffer-close!', 'replace_with_yanked', 'move_char_right']

[keys.insert.';']
# Insert various characters.
# Heavily based on qwerty-lafayette.
# https://qwerty-lafayette.org
# See also “Vim digraphs” for defaults.
# https://vimhelp.org/digraph.txt.html#digraphs-default
';' = ['collapse_selection', ':insert-output printf ";"']
q = ['collapse_selection', ':insert-output printf â']
w = ['collapse_selection', ':insert-output printf é']
W = ['collapse_selection', ':insert-output printf É']
e = ['collapse_selection', ':insert-output printf è']
u = ['collapse_selection', ':insert-output printf ù']
U = ['collapse_selection', ':insert-output printf û']
i = ['collapse_selection', ':insert-output printf î']
I = ['collapse_selection', ':insert-output printf ï']
o = ['collapse_selection', ':insert-output printf ô']
'[' = ['collapse_selection', ':insert-output printf «']
']' = ['collapse_selection', ':insert-output printf »']
a = ['collapse_selection', ':insert-output printf à']
A = ['collapse_selection', ':insert-output printf À']
s = ['collapse_selection', ':insert-output printf ê']
f = ['collapse_selection', ':insert-output printf ë']
c = ['collapse_selection', ':insert-output printf ç']
C = ['collapse_selection', ':insert-output printf Ç']
z = ['collapse_selection', ':insert-output printf æ']
x = ['collapse_selection', ':insert-output printf œ']
'.' = ['collapse_selection', ':insert-output printf …']
space = ['collapse_selection', ':insert-output printf ’']
'<' = ['collapse_selection', ':insert-output printf “']
'>' = ['collapse_selection', ':insert-output printf ”']
minus = ['collapse_selection', ':insert-output printf —']
